name: Build ysh (meson)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
